spring.application.name=maverick-bank

# DB Connection Params
spring.datasource.url=jdbc:mysql://localhost:3306/maverick_bank?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
